version: '3'
services:
  postgres-a:
    image: postgres:13-alpine
    container_name: "postgres-alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432

  postgres-b:
    image: postgres:13-alpine
    container_name: "postgres-bullseye"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 15433:5432
